# Generated by Django 3.0 on 2020-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_desc', models.CharField(max_length=500)),
                ('e_location', models.CharField(max_length=50)),
                ('e_fdate', models.DateField()),
                ('e_ftime', models.TimeField()),
                ('e_tdate', models.DateField()),
                ('e_ttime', models.TimeField()),
                ('e_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_contact', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_type', models.CharField(max_length=10)),
                ('p_tickets', models.IntegerField()),
            ],
        ),
    ]
