# Generated by Django 3.0 on 2020-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='e_desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_fdate',
            new_name='fromDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_ftime',
            new_name='fromTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_tdate',
            new_name='toDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_ttime',
            new_name='toTime',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='p_contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='p_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='p_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='p_tickets',
            new_name='Tickets',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='p_type',
            new_name='Type',
        ),
    ]
