# Generated by Django 3.0 on 2020-06-04 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200603_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fromTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='toDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='toTime',
        ),
        migrations.AddField(
            model_name='event',
            name='From',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 6, 55, 38, 905434, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='To',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 6, 55, 38, 905434, tzinfo=utc)),
        ),
    ]
