# Generated by Django 3.0 on 2020-06-04 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200604_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='From',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 7, 3, 50, 655003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='To',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 7, 3, 50, 655003, tzinfo=utc)),
        ),
    ]
