# Generated by Django 3.0 on 2020-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Email',
            new_name='hostEmail',
        ),
        migrations.AddField(
            model_name='event',
            name='hostPW',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
