# Generated by Django 3.0 on 2020-06-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Poster',
            field=models.ImageField(upload_to='media'),
        ),
    ]
