# Generated by Django 3.0 on 2020-06-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200606_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Poster',
        ),
    ]
