# Generated by Django 3.0 on 2020-06-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Poster',
        ),
    ]
