# Generated by Django 3.0 on 2020-06-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_participant_prooflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='posterLink',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
